name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
    branches:
    - main
    - 2.x.x
    paths:
    - '**.swift'
    - '**.yml'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:5.7'
          - 'swift:5.8'
          - 'swift:5.9'
#          - 'swiftlang/swift:nightly-5.10-jammy'
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    container:
      image: ${{ matrix.image }}
      env:
        REDIS_HOSTNAME: "redis"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        swift test --enable-code-coverage
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/hummingbird-redisPackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -ignore-filename-regex="\/Benchmarks\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        file: info.lcov
