name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

env:
  REDIS_HOSTNAME: redis
jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ["swift:5.9", "swift:5.10", "swift:6.0", "swiftlang/swift:nightly-6.1-jammy"]
    container:
      image: ${{ matrix.image }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift test --enable-code-coverage
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/hummingbird-redisPackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -ignore-filename-regex="\/Benchmarks\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v5
      with:
        files: info.lcov
