name: Swift nightly build

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ['nightly-focal', 'nightly-jammy', 'nightly-amazonlinux2']
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    container:
      image: swiftlang/swift:${{ matrix.image }}
      env:
        REDIS_HOSTNAME: "redis"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift test
