name: Swift nightly build

on:
  workflow_dispatch:

env:
  VALKEY_HOSTNAME: valkey
jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ['nightly-focal', 'nightly-jammy', 'nightly-amazonlinux2']
    container:
      image: swiftlang/swift:${{ matrix.image }}
    services:
      valkey:
        image: valkey/valkey
        ports:
          - 6379:6379
        options: --entrypoint valkey-server

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift test
