name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['nightly-5.6-bionic', 'nightly-5.6-focal', 'nightly-5.6-centos8', 'nightly-5.6-amazonlinux2']
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    container:
      image: swiftlang/swift:${{ matrix.image }}
      env:
        REDIS_HOSTNAME: "redis"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        swift test --enable-test-discovery
